Dynamically scale mass flux and courant number based on timestep Diagnosed mass flux and courant number are already time-integrated. So we need to adapt it to the current model timestep by applying a scale of t_run / t_diag. GEOS-IT diagnostic timestep is 450s, so when resolution >= C180, when transport timestep is 300s, scale should be 0.666667. When resolution < c180, transport timestep is 600s, scale should be 1.3333

diff --git a/run/GCHP/setCommonRunSettings.sh.template b/run/GCHP/setCommonRunSettings.sh.template
--- a/run/GCHP/setCommonRunSettings.sh.template
+++ b/run/GCHP/setCommonRunSettings.sh.template
@@ -389,18 +389,22 @@ MassFlux_Entry=$(grep "MFXC" ExtData.rc || echo "missing")
 if [[ ${MassFlux_Entry} != "missing" ]]; then
 
     #### Get met grid res (assume GEOS-IT and GEOS-FP are the only options)
-    C180_Entry=$(grep "MFXC.*C180x180x6" ExtData.rc || echo "missing")
+    C180_Entry=$(grep "MFXC.*C180" ExtData.rc || echo "missing")
     if [[ ${C180_Entry} != "missing" ]]; then
-	input_res=180
+        #### Dynamically scale mass flux and courant number for only GEOS-IT for now
+        trans_timestep_scale=$(echo "scale=7; ${TransConv_Timestep_sec} / 450" | bc)
+        sed -i -e "0,/MFXC/ s/\(none\)[[:space:]].*\(MFXC\)/\1 ${trans_timestep_scale} \2/" ExtData.rc
+        sed -i -e "0,/CX/ s/\(none\)[[:space:]].*\(CX\)/\1 ${trans_timestep_scale} \2/" ExtData.rc
+        input_res=180
     else
-	input_res=720
+        input_res=720
     fi
     if (( ${CS_RES} < ${input_res} )); then
-	lowest_res=${CS_RES}
-	highest_res=${input_res}
+        lowest_res=${CS_RES}
+        highest_res=${input_res}
     else
-	lowest_res=${input_res}
-	highest_res=${CS_RES}
+        lowest_res=${input_res}
+        highest_res=${CS_RES}
     fi
 
     #### Check that not using stretched grid
